### ISSUE TITLE
Standard deviation or variance in 1D example

### ISSUE THREAD

**Issue by lrozo** [judelo/gmmot#1]
Hi @judelo ,

First of all, really nice paper and code! :) 

I have been checking your notebooks and I have a kind of silly question: in all your functionalities to compute the distances, transport plans, etc, you consider that the Sigma (S0, S1) are covariance matrices. My confusion comes in the [1-D example](https://github.com/judelo/gmmot/blob/master/python/GMM_OT_introduction.ipynb). When you compute the densities using 
`densite_theorique(mu0,S0,pi0,x)` or `densite_theorique(mu1,S1,pi1,x)`, you are basically calling the PDF function from `scipy.stats.norm`. However, this function receives the standard deviation and not the variance. As you use `S0` and `S1` as (co)variance (matrices) scalars, then I was wondering if this might be an error. 

Am I missing something here? 

Leonel

**Comment by judelo** [comment]
Hi Leonel, 

You're not missing anything, you are completely right, it was an error. I corrected this and uploaded the new version. Now the function `densite_theorique` takes a variance as input and not a standard deviation. The 1D experiment is still the same with the correct variances.  

Thanks a lot for this observation !
Julie
